### ISSUE TITLE
Next Gen Xbox Improved games list

### ISSUE THREAD

**Issue by filgaia** [filgaia/my-game-collection-viewer#36]
- Manually create the Xbox improved games list of two types of tags:
- FPS Boost
- Xbox series X/S version
- 360 and Xbox one or next ver

**TODO in Web**
- [x] Upgrade libraries versions to do it
- [x] Fix Eslint issues and remove build flag `DISABLE_ESLINT_PLUGIN=true`
- [x] Fix the only test
- [ ] Implement manually the JSON for the FPS Boost Games
- [ ] Add new section (Xbox games) and load it by default
- [ ] Add to the JSON the Xbox Series Enhanced Games
